version: '3.8'

services:
  report-relay:
    build: .
    container_name: report-relay
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
